const fs = require('fs');

const path = './src/app/data.service.ts';
let content = fs.readFileSync(path, 'utf8');

const newArticlesData = `  articlesData = [
    // Part I: The Union and its Territory
    {id:'1',title:'Name and Territory of the Union',part:'Part I',desc:'India, that is Bharat, shall be a Union of States.',importance:'Foundation — establishes India\\'s name and nature of polity.', explanation:'This article declares India as a Union of States rather than a federation, emphasizing that the union is indestructible while states can be reorganized.', limitations:'None directly, but the definition of territory is subject to international law and boundary agreements.'},
    {id:'2',title:'Admission or establishment of new States',part:'Part I',desc:'Parliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit.',importance:'Enables the expansion of the Union of India.', explanation:'It grants Parliament the absolute power to admit new territories into the Indian Union (like Sikkim in 1975) without needing a constitutional amendment under Article 368.', limitations:'Must be done by law passed by Parliament; cannot be an executive action.'},
    {id:'3',title:'Formation of new States and alteration of areas, boundaries or names of existing States',part:'Part I',desc:'Parliament may form a new State, increase/diminish area of any State, or alter boundaries/names.',importance:'Provides flexibility in internal political geography.', explanation:'This article empowers Parliament to redraw the political map of India. It shows that India is an "indestructible Union of destructible states."', limitations:'A bill for this purpose must be recommended by the President, and the views of the affected state legislature must be sought (though their views are not binding).'},
    // Part II: Citizenship
    {id:'5',title:'Citizenship at the commencement of the Constitution',part:'Part II',desc:'Defines who became a citizen of India at the commencement of the Constitution.',importance:'Basis for Indian citizenship.', explanation:'It established the initial criteria for Indian citizenship on January 26, 1950, based on domicile and birth.', limitations:'Only applicable at the commencement of the Constitution; future citizenship is governed by laws made by Parliament.'},
    {id:'11',title:'Parliament to regulate the right of citizenship by law',part:'Part II',desc:'Empowers Parliament to make laws regarding acquisition and termination of citizenship.',importance:'Led to the Citizenship Act, 1955.', explanation:'Recognizing that citizenship rules need to evolve, the Constitution left future citizenship criteria entirely to Parliament.', limitations:'Subject to judicial review if it violates fundamental rights like Article 14 (Equality).'},
    // Part III: Fundamental Rights
    {id:'12',title:'Definition of "The State"',part:'Part III',desc:'Defines "the State" which includes Government and Parliament of India, Government and Legislature of states, and all local authorities.',importance:'Determines against whom fundamental rights can be enforced.', explanation:'Fundamental rights are generally claimed against the State. This article broadly defines what constitutes the State, ensuring citizens are protected against various government bodies and agencies.', limitations:'Does not usually apply to private individuals or private corporations unless they perform public functions.'},
    {id:'13',title:'Laws inconsistent with or in derogation of the fundamental rights',part:'Part III',desc:'Any law that violates fundamental rights shall be void.',importance:'Establishes the supremacy of Fundamental Rights and judicial review.', explanation:'This gives teeth to fundamental rights by empowering courts to strike down laws (pre-constitution or post-constitution) that infringe on these rights.', limitations:'Constitutional amendments were historically debated under this, but the Kesavananda Bharati case clarified that amendments can be made as long as the "Basic Structure" is not destroyed.'},
    {id:'14',title:'Equality Before Law',part:'Part III',desc:'The State shall not deny to any person equality before the law or equal protection of the laws.',importance:'Cornerstone of India\\'s democratic fabric and rule of law.', explanation:'Ensures that the law applies equally to all, irrespective of status, and that equals are treated equally. It embodies the Rule of Law.', limitations:'Not absolute. The State can make reasonable classifications based on intelligible differentia (e.g., taxing rich and poor differently).'},
    {id:'15',title:'Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth',part:'Part III',desc:'The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, or place of birth.',importance:'Ensures social equality and prohibits untouchability practices indirectly.', explanation:'Aims to dismantle historical social discrimination and ensures equal access to public places like shops, restaurants, and wells.', limitations:'The State can make special provisions for women, children, socially and educationally backward classes (OBCs), SCs, and STs (e.g., reservations).'},
    {id:'16',title:'Equality of opportunity in matters of public employment',part:'Part III',desc:'There shall be equality of opportunity for all citizens in matters relating to employment under the State.',importance:'Provides for reservations and equal access to government jobs.', explanation:'Guarantees equal chance to compete for government jobs without discrimination.', limitations:'The State can implement reservations in appointments or posts for any backward class of citizens not adequately represented in the services.'},
    {id:'17',title:'Abolition of Untouchability',part:'Part III',desc:'"Untouchability" is abolished and its practice in any form is forbidden.',importance:'Historic step to eradicate the caste-based social evil.', explanation:'An absolute prohibition against the historical practice of untouchability, making its enforcement a punishable offense.', limitations:'This is one of the few absolute rights with no formal constitutional exceptions, though enforcing laws like the SC/ST Act defines the specific penalties.'},
    {id:'18',title:'Abolition of titles',part:'Part III',desc:'No title, not being a military or academic distinction, shall be conferred by the State.',importance:'Promotes equality of status among citizens.', explanation:'Prevents the creation of a nobility or privileged class (like Sir, Nawab, Maharaja) to maintain social equality.', limitations:'Military (Param Vir Chakra) and academic (Dr., Prof.) titles are allowed. Awards like Bharat Ratna or Padma Vibhushan are not considered titles under this article.'},
    {id:'19',title:'Protection of certain rights regarding freedom of speech, etc.',part:'Part III',desc:'Guarantees six freedoms: Speech & Expression, Assembly, Association, Movement, Residence, and Profession.',importance:'The most vital article protecting civil liberties.', explanation:'Forms the core of democratic freedoms, allowing citizens to express themselves, protest peacefully, form unions, and travel or reside anywhere in India.', limitations:'Highly restricted. The State can impose "reasonable restrictions" on grounds like sovereignty and integrity of India, security of the State, public order, decency, morality, or contempt of court.'},
    {id:'20',title:'Protection in respect of conviction for offences',part:'Part III',desc:'Protects against ex post facto laws, double jeopardy, and self-incrimination.',importance:'Safeguards rights of the accused.', explanation:'Ensures you cannot be punished for an act that wasn\\'t a crime when committed, cannot be punished twice for the same offense, and cannot be forced to testify against yourself.', limitations:'Double jeopardy only applies to judicial punishments, not departmental proceedings. Self-incrimination protection doesn\\'t cover giving DNA, fingerprints, or physical evidence.'},
    {id:'21',title:'Protection of Life and Personal Liberty',part:'Part III',desc:'No person shall be deprived of his life or personal liberty except according to procedure established by law.',importance:'Called the "most fundamental" article. Expanded to include Right to Privacy, Health, Clean Environment.', explanation:'The Supreme Court has vastly expanded this article to mean the right to live with human dignity, not just mere animal existence. It includes privacy, clean air, and rapid trials.', limitations:'Can be restricted according to "procedure established by law," which the courts have ruled must be fair, just, and reasonable (due process). Cannot be suspended even during an Emergency.'},
    {id:'21A',title:'Right to Education',part:'Part III',desc:'The State shall provide free and compulsory education to all children of the age of 6 to 14 years.',importance:'Makes elementary education a fundamental right.', explanation:'Added by the 86th Amendment, it shifted education from a directive principle to an enforceable fundamental right for young children.', limitations:'Applies only to children between 6 and 14 years. Quality and implementation are subject to the Right to Education (RTE) Act.'},
    {id:'22',title:'Protection against arrest and detention in certain cases',part:'Part III',desc:'Grants protection to persons who are arrested or detained. Prevents arbitrary arrests.',importance:'Balances state security with individual liberty.', explanation:'Requires that an arrested person be informed of the grounds of arrest, allowed a lawyer, and produced before a magistrate within 24 hours.', limitations:'These protections do NOT apply to enemy aliens or persons arrested under Preventive Detention laws (where someone can be held without trial for months to prevent future crimes).'},
    {id:'23',title:'Prohibition of traffic in human beings and forced labour',part:'Part III',desc:'Traffic in human beings and begar (forced labour) are prohibited.',importance:'Protects vulnerable sections from exploitation.', explanation:'Bans slavery, human trafficking, and "begar" (compulsory work without pay).', limitations:'The State can impose compulsory service for public purposes (like military conscription or social service), but cannot discriminate on religion, race, caste, or class.'},
    {id:'24',title:'Prohibition of employment of children in factories, etc.',part:'Part III',desc:'No child below the age of 14 years shall be employed to work in any factory or mine or engaged in any other hazardous employment.',importance:'Crucial for child rights and welfare.', explanation:'Aims to protect children from hazardous work environments that endanger their health and deny them education.', limitations:'Does not prohibit children from working in harmless or non-hazardous jobs, though the Child Labour Act heavily regulates all child employment.'},
    {id:'25',title:'Freedom of conscience and free profession, practice and propagation of religion',part:'Part III',desc:'All persons are equally entitled to freedom of conscience and the right freely to profess, practice, and propagate religion.',importance:'Forms the basis of Indian secularism.', explanation:'Guarantees inner freedom of thought and the outer freedom to practice and preach one\\'s religion.', limitations:'Subject to public order, morality, and health. The State can also regulate secular activities (economic, political) associated with religious practice.'},
    {id:'26',title:'Freedom to manage religious affairs',part:'Part III',desc:'Every religious denomination shall have the right to establish and maintain institutions for religious and charitable purposes.',importance:'Grants autonomy to religious institutions.', explanation:'Protects the rights of religious groups to manage their own affairs in matters of religion and own property.', limitations:'Subject to public order, morality, and health. The State can acquire property owned by religious institutions under law.'},
    {id:'27',title:'Freedom as to payment of taxes for promotion of any particular religion',part:'Part III',desc:'No person shall be compelled to pay any taxes for the promotion of any particular religion.',importance:'Ensures state remains secular in taxation.', explanation:'The State cannot use public tax money to fund or promote any specific religion, ensuring financial secularism.', limitations:'Prohibits only taxes, not fees. The State can charge fees to provide services to pilgrims or maintain safety at religious gatherings.'},
    {id:'28',title:'Freedom as to attendance at religious instruction in certain educational institutions',part:'Part III',desc:'No religious instruction shall be provided in any educational institution wholly maintained out of State funds.',importance:'Separates religion from state-funded education.', explanation:'Ensures that government schools remain completely secular and do not impart religious teachings.', limitations:'Does not apply to institutions administered by the State but established under an endowment or trust requiring religious instruction.'},
    {id:'29',title:'Protection of interests of minorities',part:'Part III',desc:'Any section of citizens having a distinct language, script or culture of its own shall have the right to conserve the same.',importance:'Protects cultural diversity of India.', explanation:'Allows linguistic and cultural minorities to take steps to preserve their unique identity.', limitations:'No citizen can be denied admission to state-funded educational institutions solely on grounds of religion, race, caste, or language.'},
    {id:'30',title:'Right of minorities to establish and administer educational institutions',part:'Part III',desc:'All minorities, whether based on religion or language, shall have the right to establish and administer educational institutions of their choice.',importance:'Empowers minorities to preserve their culture through education.', explanation:'Gives minorities the autonomy to run educational institutions to preserve their culture and language.', limitations:'The State can still impose reasonable regulations regarding academic standards, health, and sanitation.'},
    {id:'32',title:'Remedies for enforcement of rights conferred by this Part',part:'Part III',desc:'The right to move the Supreme Court by appropriate proceedings for the enforcement of Fundamental Rights.',importance:'Dr. Ambedkar called it the "heart and soul" of the Constitution.', explanation:'Provides the constitutional remedy (via writs like Habeas Corpus, Mandamus) to directly approach the Supreme Court if your fundamental rights are violated.', limitations:'Can be suspended when a National Emergency is declared under Article 352 (except Articles 20 and 21).'},
    // Directive Principles of State Policy
    {id:'36',title:'Definition of State for DPSP',part:'Part IV',desc:'In this Part, unless the context otherwise requires, "the State" has the same meaning as in Part III.',importance:'Sets scope for DPSP implementation.', explanation:'Clarifies that the same government bodies responsible for upholding Fundamental Rights are also responsible for applying Directive Principles.', limitations:'None.'},
    {id:'39',title:'Certain principles of policy to be followed by the State',part:'Part IV',desc:'State shall direct its policy towards securing adequate means of livelihood, equal pay for equal work, etc.',importance:'Provides a socialist blueprint for the welfare state.', explanation:'Lays down comprehensive economic and social guidelines, including preventing the concentration of wealth and ensuring equal pay for equal work for men and women.', limitations:'Like all DPSPs, it is non-justiciable (cannot be enforced in court).'},
    {id:'39A',title:'Equal justice and free legal aid',part:'Part IV',desc:'The State shall secure that the operation of the legal system promotes justice, and shall provide free legal aid.',importance:'Ensures justice is not denied due to poverty.', explanation:'Added by the 42nd Amendment, it mandates the State to provide free legal assistance to the poor to ensure equal access to justice.', limitations:'Non-justiciable; depends on state resources and implementation through authorities like NALSA.'},
    {id:'40',title:'Organisation of village panchayats',part:'Part IV',desc:'The State shall take steps to organize village panchayats and endow them with powers of self-government.',importance:'Gandhian principle of decentralized democracy.', explanation:'Reflects Mahatma Gandhi\\'s vision of Gram Swaraj (village self-rule). It eventually led to the 73rd Amendment Act establishing the Panchayati Raj system.', limitations:'Non-justiciable until implemented by the 73rd Amendment in 1992.'},
    {id:'44',title:'Uniform Civil Code for the citizens',part:'Part IV',desc:'The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.',importance:'Aims at national integration and gender justice.', explanation:'Directs the State to implement a common set of personal laws (marriage, divorce, inheritance) for all citizens, regardless of religion.', limitations:'Highly debated and remains a directive rather than an enforceable law (except in Goa).'},
    {id:'45',title:'Provision for early childhood care and education',part:'Part IV',desc:'The State shall endeavour to provide early childhood care and education for all children until they complete the age of 6 years.',importance:'Focuses on early childhood development.', explanation:'After Article 21A made education for 6-14 year olds a fundamental right, this article was amended to focus on early childhood care (0-6 years).', limitations:'Non-justiciable; relies on schemes like Anganwadi.'},
    {id:'46',title:'Promotion of educational and economic interests of SC, ST and other weaker sections',part:'Part IV',desc:'The State shall promote with special care the educational and economic interests of the weaker sections of the people.',importance:'Basis for affirmative action policies.', explanation:'Provides the constitutional backing for welfare schemes, scholarships, and reservations for marginalized communities.', limitations:'Must be balanced against overall administrative efficiency and the fundamental rights of others.'},
    {id:'50',title:'Separation of judiciary from executive',part:'Part IV',desc:'The State shall take steps to separate the judiciary from the executive in the public services of the State.',importance:'Ensures judicial independence.', explanation:'Aims to prevent the concentration of power by ensuring that executive officers do not exercise judicial powers, ensuring fair trials.', limitations:'Non-justiciable.'},
    {id:'51',title:'Promotion of international peace and security',part:'Part IV',desc:'The State shall endeavour to promote international peace, security, and maintain just and honourable relations between nations.',importance:'Guides India\\'s foreign policy.', explanation:'Lays the foundation for India\\'s foreign policy, advocating for peaceful coexistence, respect for international law, and arbitration of disputes.', limitations:'Non-justiciable.'},
    // Fundamental Duties
    {id:'51A',title:'Fundamental Duties',part:'Part IVA',desc:'It shall be the duty of every citizen of India to abide by the Constitution, respect its ideals, and protect the sovereignty of India. (Contains 11 duties)',importance:'Reminds citizens that rights come with responsibilities.', explanation:'Added during the Emergency by the 42nd Amendment, these duties remind citizens that they owe obligations to the nation and society in exchange for their rights.', limitations:'Non-justiciable; citizens cannot be directly penalized by courts for merely failing to perform a duty, though Parliament can pass laws to enforce them.'},
    // Other Key Articles
    {id:'52',title:'The President of India',part:'Part V',desc:'There shall be a President of India.',importance:'Establishes the office of the Head of State.', explanation:'Formally creates the office of the President, who is the head of the Indian State and the symbol of the nation\\'s unity.', limitations:'The President is a nominal head and generally must act on the aid and advice of the Council of Ministers.'},
    {id:'72',title:'Power of President to grant pardons, etc.',part:'Part V',desc:'The President shall have the power to grant pardons, reprieves, respites or remissions of punishment.',importance:'Provides an executive check on judicial errors.', explanation:'Gives the President the power of clemency, acting as a final safeguard against potential judicial errors, especially in death penalty cases.', limitations:'Pardoning power is exercised on the advice of the Council of Ministers, not at the personal discretion of the President, and is subject to limited judicial review.'},
    {id:'74',title:'Council of Ministers to aid and advise President',part:'Part V',desc:'There shall be a Council of Ministers with the Prime Minister at the head to aid and advise the President.',importance:'Establishes the parliamentary form of government.', explanation:'The bedrock of India\\'s parliamentary system. It mandates that the real executive power lies with the Prime Minister and the cabinet, not the President.', limitations:'The advice tendered by the Ministers cannot be inquired into by any court.'},
    {id:'110',title:'Definition of "Money Bills"',part:'Part V',desc:'A Bill shall be deemed to be a Money Bill if it contains only provisions dealing with taxation, borrowing, etc.',importance:'Defines the special legislative process for financial matters.', explanation:'Creates a specific category of legislation for core financial matters, granting the Lok Sabha exclusive power over the nation\\'s purse strings.', limitations:'The Rajya Sabha has severely restricted powers regarding Money Bills; it can only recommend changes within 14 days, which the Lok Sabha can reject.'},
    {id:'124',title:'Establishment and constitution of Supreme Court',part:'Part V',desc:'There shall be a Supreme Court of India consisting of a Chief Justice of India and other Judges.',importance:'Establishes the highest judicial body of the country.', explanation:'Creates the apex court, outlining the appointment, qualifications, and removal of judges to ensure an independent judiciary.', limitations:'Judges can only be removed through a stringent impeachment process in Parliament, safeguarding their independence.'},
    {id:'153',title:'Governors of States',part:'Part VI',desc:'There shall be a Governor for each State.',importance:'Establishes the executive head of the state.', explanation:'Creates the office of the Governor, who acts as the constitutional head of the state government and a representative of the Union government.', limitations:'Like the President, the Governor generally acts on the advice of the State Council of Ministers, though they have certain discretionary powers.'},
    {id:'213',title:'Power of Governor to promulgate Ordinances during recess of Legislature',part:'Part VI',desc:'If the Legislature is not in session, the Governor can promulgate Ordinances having the same force as an Act.',importance:'Allows immediate legislative action in emergencies.', explanation:'Empowers the state executive to enact temporary laws when the state assembly is not in session to deal with urgent situations.', limitations:'Ordinances are temporary and must be approved by the state legislature within six weeks of its reassembly.'},
    {id:'226',title:'Power of High Courts to issue certain writs',part:'Part VI',desc:'Every High Court shall have power to issue writs for the enforcement of Fundamental Rights and for any other purpose.',importance:'Provides broader writ jurisdiction to High Courts than the Supreme Court.', explanation:'Allows citizens to approach High Courts not just for fundamental rights violations (like Article 32), but also for ordinary legal rights violations.', limitations:'High Courts can generally only issue writs within their territorial jurisdiction.'},
    {id:'246',title:'Subject-matter of laws made by Parliament and by the Legislatures of States',part:'Part XI',desc:'Distributes legislative powers between Union and States (Union List, State List, Concurrent List).',importance:'Defines the federal structure of India.', explanation:'The core of Indian federalism. It divides law-making powers across three lists in the Seventh Schedule, detailing what the center and states can legislate on.', limitations:'In case of conflict over matters in the Concurrent List, central law prevails over state law.'},
    {id:'280',title:'Finance Commission',part:'Part XII',desc:'The President shall constitute a Finance Commission to recommend the distribution of tax revenues between Union and States.',importance:'Ensures equitable financial distribution.', explanation:'Establishes an expert body every five years to determine how tax revenues collected by the Center should be shared with and among the states.', limitations:'The Commission\\'s recommendations are advisory, though they are usually accepted by the government.'},
    {id:'324',title:'Superintendence, direction and control of elections to be vested in an Election Commission',part:'Part XV',desc:'The power of elections shall be vested in the Election Commission.',importance:'Ensures free and fair elections.', explanation:'Creates an independent Election Commission to oversee the massive democratic exercise of elections to Parliament and state legislatures.', limitations:'The Constitution does not prescribe specific qualifications or a fixed term for the Election Commissioners, leaving it to Parliament to determine.'},
    {id:'352',title:'Proclamation of Emergency',part:'Part XVIII',desc:'If the President is satisfied that a grave emergency exists whereby the security of India is threatened, he may proclaim an emergency.',importance:'Provides mechanism to deal with national crises.', explanation:'Allows the federal structure to convert into a unitary one during war, external aggression, or armed rebellion, centralizing immense power.', limitations:'Heavily amended after 1977 to prevent misuse; requires a written recommendation from the Cabinet and approval by special majority in Parliament within one month.'},
    {id:'356',title:'Provisions in case of failure of constitutional machinery in States',part:'Part XVIII',desc:'President\\'s Rule can be imposed in a State if its government cannot be carried on in accordance with the Constitution.',importance:'Maintains constitutional order in states (often debated for misuse).', explanation:'Allows the Central government to dismiss a state government and impose "President\\'s Rule" if constitutional governance fails in that state.', limitations:'The S.R. Bommai judgment (1994) placed strict limitations on this power, making its use subject to judicial review to prevent arbitrary dismissals of opposition state governments.'},
    {id:'368',title:'Power of Parliament to amend the Constitution and procedure therefor',part:'Part XX',desc:'Parliament may in exercise of its constituent power amend by way of addition, variation or repeal any provision of this Constitution.',importance:'Allows the Constitution to be a living document.', explanation:'Provides the procedure to change the Constitution, ensuring it can adapt to changing times while preventing frivolous alterations.', limitations:'Parliament CANNOT amend the "Basic Structure" of the Constitution (e.g., democracy, secularism, judicial review), as established in the Kesavananda Bharati case.'},
    {id:'370',title:'Temporary provisions with respect to the State of Jammu and Kashmir',part:'Part XXI',desc:'(Abrogated in 2019) Granted special autonomous status to Jammu and Kashmir.',importance:'Historical significance regarding India\\'s integration.', explanation:'Historically granted a separate constitution and significant autonomy to J&K. This status was effectively revoked in August 2019.', limitations:'Was explicitly listed as a "temporary" provision; its operative powers have now been abrogated, fully integrating J&K\\'s laws with the rest of India.'}
  ];`;

const regex = /articlesData = \[\s*\/\/ Part I: The Union and its Territory[\s\S]*?\];/;
const newContent = content.replace(regex, newArticlesData);

fs.writeFileSync(path, newContent, 'utf8');
console.log('Replaced articlesData in data.service.ts successfully!');
